package com.vythera.vyxelapps

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // ── Navigation ────────────────────────────────────────────────────────────
    val navHome: String = "Home",
    val navSearch: String = "Search",
    val navInstalled: String = "Installed",
    val navProfile: String = "Profile",
    val navSettings: String = "Settings",
    // ── Search screen ─────────────────────────────────────────────────────────
    val searchHint: String = "Search GitHub, GitLab, F-Droid…",
    val trendingApps: String = "Trending Apps",
    val allSources: String = "All Sources",
    val searching: String = "Searching all sources…",
    val fetchingMore: String = "Fetching from more sources…",
    val noResultsFound: String = "No results found",
    val tryDifferent: String = "Try different terms or remove some filters",
    // ── Actions ───────────────────────────────────────────────────────────────
    val install: String = "Install",
    val download: String = "Download",
    val downloadOnly: String = "Download Only",
    val uninstall: String = "Uninstall",
    val cancel: String = "Cancel",
    val save: String = "Save",
    val edit: String = "Edit",
    val retry: String = "Try Again",
    val apply: String = "Apply",
    val refresh: String = "Refresh",
    val back: String = "Back",
    val skipVersion: String = "Skip this version",
    val checkingRelease: String = "Checking latest release…",
    val stableRelease: String = "Stable release",
    val whatsNew: String = "What's new",
    val noApkFound: String = "No APK found in this release.",
    val downloading: String = "Downloading…",
    // ── App detail ────────────────────────────────────────────────────────────
    val stars: String = "Stars",
    val forks: String = "Forks",
    val codingLanguage: String = "Language",
    val about: String = "About",
    val translate: String = "Translate",
    val compare: String = "Compare",
    val version: String = "Version",
    val featured: String = "FEATURED",
    val openInBrowser: String = "Open in Browser",
    val updateAvailable: String = "Update Available",
    val installedBadge: String = "✓  Installed",
    val screenshots: String = "Screenshots",
    val release: String = "Release",
    val noDescAvailable: String = "No description available.",
    val translatedRedo: String = "Translated · Redo",
    // ── Home sections ─────────────────────────────────────────────────────────
    val sectionRecommended: String = "⭐ Recommended for You",
    val sectionTrending: String = "🔥 Trending Now",
    val sectionMedia: String = "🎬 Media & Entertainment",
    val sectionTools: String = "🛠 Tools & Utilities",
    val sectionGames: String = "🎮 Games & Emulators",
    val sectionBrowsers: String = "🌐 Browsers & Privacy",
    val sectionProductivity: String = "📋 Productivity",
    val sectionSecurity: String = "🔒 Security",
    val sectionDevTools: String = "💻 Dev Tools",
    val sectionPhotoVideo: String = "📸 Photo & Video",
    val sectionMusic: String = "🎵 Music & Audio",
    val sectionFinance: String = "💰 Finance",
    val sectionEducation: String = "📚 Education",
    val sectionFitness: String = "💪 Fitness & Health",
    val sectionArtDesign: String = "🎨 Art & Design",
    val sectionNews: String = "🗞 News",
    val sectionSocial: String = "💬 Social",
    val sectionCloudStorage: String = "☁️ Cloud Storage",
    val sectionCooking: String = "🍳 Cooking & Food",
    // ── Settings ──────────────────────────────────────────────────────────────
    val settingsTitle: String = "Settings",
    val appearance: String = "APPEARANCE",
    val themeColor: String = "THEME COLOR",
    val fontSection: String = "FONT",
    val languageSection: String = "LANGUAGE",
    val githubSection: String = "GITHUB",
    val aboutSection: String = "ABOUT",
    val amoledOverride: String = "AMOLED Override",
    val amoledOverrideDesc: String = "Force pure black backgrounds on any dark theme",
    val materialYou: String = "Material You (Monet)",
    val materialYouDesc: String = "Derives accent, containers & tonal surfaces from your wallpaper palette",
    val personalAccessToken: String = "Personal Access Token",
    val tokenRequired: String = "Required for GitHub search to work",
    val saveToken: String = "Save Token",
    val versionLabel: String = "Version",
    val followSystem: String = "📱  Follow System",
    // ── Profile ───────────────────────────────────────────────────────────────
    val profileTitle: String = "Profile",
    val displayName: String = "Display name",
    val emailAddress: String = "Email address",
    val supportFeedbackTitle: String = "Support & Feedback",
    val sendFeedback: String = "Send Feedback",
    val sendFeedbackDesc: String = "Suggest features or report bugs",
    val supportProject: String = "Support the Project",
    val supportProjectDesc: String = "Star on GitHub or contribute",
    val shareVyxel: String = "Share Vyxel",
    val shareVyxelDesc: String = "Tell your friends about it",
    val favourites: String = "Favourites",
    val recentlyViewed: String = "Recently Viewed",
    val installHistory: String = "Install History",
    val installHistoryHint: String = "Tap any version to reinstall it",
    val checkForUpdates: String = "Check for Updates",
    val updatesAvailable: String = "Updates Available",
    val guestUser: String = "Guest User",
    // ── Installed screen ──────────────────────────────────────────────────────
    val installedTitle: String = "Installed",
    val nothingInstalled: String = "Nothing installed yet",
    val nothingInstalledDesc: String = "Apps you install through Vyxel\nwill appear here",
    val installedStatus: String = "Installed",
    val removedStatus: String = "Removed",
    // ── Misc ──────────────────────────────────────────────────────────────────
    val loadingApps: String = "Loading apps from all sources…",
    val pressBackToExit: String = "Press back again to exit",
    val noApkAvailable: String = "No APK Available",
    val translateTo: String = "Translate to",
)

val LocalStrings = compositionLocalOf { AppStrings() }

@Suppress("LongMethod")
fun stringsForLanguage(language: String): AppStrings = when (language) {

    "Hindi" -> AppStrings(
        navHome = "होम", navSearch = "खोजें", navInstalled = "इंस्टॉल्ड",
        navProfile = "प्रोफाइल", navSettings = "सेटिंग्स",
        searchHint = "GitHub, GitLab, F-Droid में खोजें…",
        trendingApps = "ट्रेंडिंग ऐप्स", allSources = "सभी स्रोत",
        searching = "सभी स्रोतों में खोज रहे हैं…",
        fetchingMore = "अधिक स्रोतों से ला रहे हैं…",
        noResultsFound = "कोई परिणाम नहीं मिला",
        tryDifferent = "अलग शब्द या कम फ़िल्टर आज़माएं",
        install = "इंस्टॉल", download = "डाउनलोड", downloadOnly = "केवल डाउनलोड",
        uninstall = "अनइंस्टॉल", cancel = "रद्द करें", save = "सहेजें",
        edit = "संपादित", retry = "पुनः प्रयास", apply = "लागू करें", refresh = "रीफ्रेश",
        back = "वापस", skipVersion = "इस संस्करण को छोड़ें",
        checkingRelease = "नवीनतम रिलीज़ जाँच रहे हैं…",
        stableRelease = "स्थिर रिलीज़", whatsNew = "नया क्या है",
        noApkFound = "इस रिलीज़ में कोई APK नहीं मिला।",
        downloading = "डाउनलोड हो रहा है…",
        stars = "स्टार्स", forks = "फोर्क्स", codingLanguage = "भाषा",
        about = "के बारे में", translate = "अनुवाद", compare = "तुलना",
        version = "संस्करण", featured = "फीचर्ड", openInBrowser = "ब्राउज़र में खोलें",
        updateAvailable = "अपडेट उपलब्ध", installedBadge = "✓  इंस्टॉल्ड",
        screenshots = "स्क्रीनशॉट", release = "रिलीज़",
        noDescAvailable = "कोई विवरण उपलब्ध नहीं।",
        translatedRedo = "अनुवादित · फिर से करें",
        sectionRecommended = "⭐ आपके लिए अनुशंसित",
        sectionTrending = "🔥 ट्रेंडिंग अभी",
        sectionMedia = "🎬 मीडिया और मनोरंजन",
        sectionTools = "🛠 टूल्स और यूटिलिटीज़",
        sectionGames = "🎮 गेम्स और एमुलेटर",
        sectionBrowsers = "🌐 ब्राउज़र और प्राइवेसी",
        sectionProductivity = "📋 उत्पादकता",
        sectionSecurity = "🔒 सुरक्षा",
        sectionDevTools = "💻 डेव टूल्स",
        sectionPhotoVideo = "📸 फोटो और वीडियो",
        sectionMusic = "🎵 म्यूज़िक और ऑडियो",
        sectionFinance = "💰 वित्त",
        sectionEducation = "📚 शिक्षा",
        sectionFitness = "💪 फिटनेस और स्वास्थ्य",
        sectionArtDesign = "🎨 कला और डिज़ाइन",
        sectionNews = "🗞 समाचार",
        sectionSocial = "💬 सोशल",
        sectionCloudStorage = "☁️ क्लाउड स्टोरेज",
        sectionCooking = "🍳 खाना और रेसिपी",
        settingsTitle = "सेटिंग्स", appearance = "दिखावट", themeColor = "थीम रंग",
        fontSection = "फ़ॉन्ट", languageSection = "भाषा",
        githubSection = "GITHUB", aboutSection = "के बारे में",
        amoledOverride = "AMOLED ओवरराइड",
        amoledOverrideDesc = "किसी भी डार्क थीम पर शुद्ध काला बैकग्राउंड",
        materialYou = "Material You (Monet)",
        materialYouDesc = "वॉलपेपर से एक्सेंट और टोनल रंग प्राप्त करें",
        personalAccessToken = "Personal Access Token",
        tokenRequired = "GitHub खोज के लिए आवश्यक",
        saveToken = "टोकन सहेजें", versionLabel = "संस्करण",
        followSystem = "📱  सिस्टम फॉलो करें",
        profileTitle = "प्रोफाइल", displayName = "नाम", emailAddress = "ईमेल",
        supportFeedbackTitle = "सहायता और फीडबैक", sendFeedback = "फीडबैक भेजें",
        sendFeedbackDesc = "सुझाव या बग रिपोर्ट करें",
        supportProject = "प्रोजेक्ट सपोर्ट करें",
        supportProjectDesc = "GitHub पर स्टार करें या योगदान दें",
        shareVyxel = "Vyxel शेयर करें",
        shareVyxelDesc = "दोस्तों को बताएं", favourites = "पसंदीदा",
        recentlyViewed = "हाल ही में देखा", installHistory = "इंस्टॉल इतिहास",
        installHistoryHint = "पुनः इंस्टॉल करने के लिए टैप करें",
        checkForUpdates = "अपडेट जांचें", updatesAvailable = "अपडेट उपलब्ध",
        guestUser = "अतिथि उपयोगकर्ता",
        installedTitle = "इंस्टॉल्ड", nothingInstalled = "अभी कुछ इंस्टॉल नहीं",
        nothingInstalledDesc = "Vyxel से इंस्टॉल किए गए ऐप्स\nयहाँ दिखेंगे",
        installedStatus = "इंस्टॉल्ड", removedStatus = "हटाया गया",
        loadingApps = "सभी स्रोतों से ऐप्स लोड हो रहे हैं…",
        pressBackToExit = "बाहर निकलने के लिए फिर से दबाएं",
        noApkAvailable = "APK उपलब्ध नहीं", translateTo = "में अनुवाद करें",
    )

    "Spanish" -> AppStrings(
        navHome = "Inicio", navSearch = "Buscar", navInstalled = "Instalado",
        navProfile = "Perfil", navSettings = "Ajustes",
        searchHint = "Buscar en GitHub, GitLab, F-Droid…",
        trendingApps = "Aplicaciones Populares", allSources = "Todas las Fuentes",
        searching = "Buscando en todas las fuentes…",
        fetchingMore = "Obteniendo de más fuentes…",
        noResultsFound = "No se encontraron resultados",
        tryDifferent = "Prueba otros términos o elimina filtros",
        install = "Instalar", download = "Descargar", downloadOnly = "Solo Descargar",
        uninstall = "Desinstalar", cancel = "Cancelar", save = "Guardar",
        edit = "Editar", retry = "Reintentar", apply = "Aplicar", refresh = "Actualizar",
        back = "Volver", skipVersion = "Saltar esta versión",
        checkingRelease = "Verificando última versión…",
        stableRelease = "Versión estable", whatsNew = "Novedades",
        noApkFound = "No se encontró APK en esta versión.",
        downloading = "Descargando…",
        stars = "Estrellas", forks = "Bifurcaciones", codingLanguage = "Lenguaje",
        about = "Acerca de", translate = "Traducir", compare = "Comparar",
        version = "Versión", featured = "DESTACADO", openInBrowser = "Abrir en Navegador",
        updateAvailable = "Actualización Disponible", installedBadge = "✓  Instalado",
        screenshots = "Capturas", release = "Versión",
        noDescAvailable = "Sin descripción disponible.",
        translatedRedo = "Traducido · Rehacer",
        sectionRecommended = "⭐ Recomendado para Ti",
        sectionTrending = "🔥 Tendencias",
        sectionMedia = "🎬 Medios y Entretenimiento",
        sectionTools = "🛠 Herramientas", sectionGames = "🎮 Juegos y Emuladores",
        sectionBrowsers = "🌐 Navegadores y Privacidad",
        sectionProductivity = "📋 Productividad", sectionSecurity = "🔒 Seguridad",
        sectionDevTools = "💻 Herramientas Dev", sectionPhotoVideo = "📸 Foto y Vídeo",
        sectionMusic = "🎵 Música y Audio", sectionFinance = "💰 Finanzas",
        sectionEducation = "📚 Educación", sectionFitness = "💪 Fitness y Salud",
        sectionArtDesign = "🎨 Arte y Diseño", sectionNews = "🗞 Noticias",
        sectionSocial = "💬 Social", sectionCloudStorage = "☁️ Almacenamiento",
        sectionCooking = "🍳 Cocina y Recetas",
        settingsTitle = "Ajustes", appearance = "APARIENCIA", themeColor = "COLOR DE TEMA",
        fontSection = "FUENTE", languageSection = "IDIOMA",
        githubSection = "GITHUB", aboutSection = "ACERCA DE",
        amoledOverride = "Override AMOLED",
        amoledOverrideDesc = "Forzar fondo negro puro en cualquier tema oscuro",
        materialYou = "Material You (Monet)",
        materialYouDesc = "Obtiene colores de tu fondo de pantalla",
        personalAccessToken = "Token de Acceso Personal",
        tokenRequired = "Necesario para buscar en GitHub",
        saveToken = "Guardar Token", versionLabel = "Versión",
        followSystem = "📱  Seguir Sistema",
        profileTitle = "Perfil", displayName = "Nombre", emailAddress = "Correo electrónico",
        supportFeedbackTitle = "Soporte y Comentarios", sendFeedback = "Enviar Comentarios",
        sendFeedbackDesc = "Sugerir funciones o reportar errores",
        supportProject = "Apoyar el Proyecto",
        supportProjectDesc = "Dar estrella en GitHub o contribuir",
        shareVyxel = "Compartir Vyxel", shareVyxelDesc = "Cuéntale a tus amigos",
        favourites = "Favoritos", recentlyViewed = "Visto Recientemente",
        installHistory = "Historial de Instalación",
        installHistoryHint = "Toca para reinstalar cualquier versión",
        checkForUpdates = "Buscar Actualizaciones",
        updatesAvailable = "Actualizaciones Disponibles", guestUser = "Invitado",
        installedTitle = "Instalado", nothingInstalled = "Nada instalado aún",
        nothingInstalledDesc = "Las apps que instales con Vyxel\naparecerán aquí",
        installedStatus = "Instalado", removedStatus = "Eliminado",
        loadingApps = "Cargando apps de todas las fuentes…",
        pressBackToExit = "Pulsa atrás de nuevo para salir",
        noApkAvailable = "Sin APK Disponible", translateTo = "Traducir a",
    )

    "French" -> AppStrings(
        navHome = "Accueil", navSearch = "Rechercher", navInstalled = "Installé",
        navProfile = "Profil", navSettings = "Paramètres",
        searchHint = "Rechercher sur GitHub, GitLab, F-Droid…",
        trendingApps = "Applications Tendances", allSources = "Toutes les Sources",
        searching = "Recherche dans toutes les sources…",
        fetchingMore = "Récupération depuis d'autres sources…",
        noResultsFound = "Aucun résultat trouvé",
        tryDifferent = "Essayez d'autres termes ou supprimez des filtres",
        install = "Installer", download = "Télécharger", downloadOnly = "Télécharger Seulement",
        uninstall = "Désinstaller", cancel = "Annuler", save = "Sauvegarder",
        edit = "Modifier", retry = "Réessayer", apply = "Appliquer", refresh = "Actualiser",
        back = "Retour", skipVersion = "Ignorer cette version",
        checkingRelease = "Vérification de la dernière version…",
        stableRelease = "Version stable", whatsNew = "Nouveautés",
        noApkFound = "Aucun APK trouvé dans cette version.",
        downloading = "Téléchargement…",
        stars = "Étoiles", forks = "Forks", codingLanguage = "Langage",
        about = "À propos", translate = "Traduire", compare = "Comparer",
        version = "Version", featured = "EN VEDETTE", openInBrowser = "Ouvrir dans le Navigateur",
        updateAvailable = "Mise à Jour Disponible", installedBadge = "✓  Installé",
        screenshots = "Captures d'écran", release = "Version",
        noDescAvailable = "Aucune description disponible.",
        translatedRedo = "Traduit · Refaire",
        sectionRecommended = "⭐ Recommandé pour Vous",
        sectionTrending = "🔥 Tendances", sectionMedia = "🎬 Médias et Divertissement",
        sectionTools = "🛠 Outils", sectionGames = "🎮 Jeux et Émulateurs",
        sectionBrowsers = "🌐 Navigateurs et Confidentialité",
        sectionProductivity = "📋 Productivité", sectionSecurity = "🔒 Sécurité",
        sectionDevTools = "💻 Outils Dev", sectionPhotoVideo = "📸 Photo et Vidéo",
        sectionMusic = "🎵 Musique et Audio", sectionFinance = "💰 Finance",
        sectionEducation = "📚 Éducation", sectionFitness = "💪 Fitness et Santé",
        sectionArtDesign = "🎨 Art et Design", sectionNews = "🗞 Actualités",
        sectionSocial = "💬 Social", sectionCloudStorage = "☁️ Stockage Cloud",
        sectionCooking = "🍳 Cuisine et Recettes",
        settingsTitle = "Paramètres", appearance = "APPARENCE", themeColor = "COULEUR DU THÈME",
        fontSection = "POLICE", languageSection = "LANGUE",
        githubSection = "GITHUB", aboutSection = "À PROPOS",
        amoledOverride = "Override AMOLED",
        amoledOverrideDesc = "Forcer un fond noir pur sur tout thème sombre",
        materialYou = "Material You (Monet)",
        materialYouDesc = "Dérive les couleurs de votre fond d'écran",
        personalAccessToken = "Jeton d'Accès Personnel",
        tokenRequired = "Requis pour la recherche GitHub",
        saveToken = "Enregistrer le Jeton", versionLabel = "Version",
        followSystem = "📱  Suivre le Système",
        profileTitle = "Profil", displayName = "Nom affiché", emailAddress = "Adresse e-mail",
        supportFeedbackTitle = "Support et Commentaires", sendFeedback = "Envoyer un Commentaire",
        sendFeedbackDesc = "Suggérer des fonctionnalités ou signaler des bugs",
        supportProject = "Soutenir le Projet",
        supportProjectDesc = "Mettre une étoile sur GitHub ou contribuer",
        shareVyxel = "Partager Vyxel", shareVyxelDesc = "Parlez-en à vos amis",
        favourites = "Favoris", recentlyViewed = "Récemment Consulté",
        installHistory = "Historique d'Installation",
        installHistoryHint = "Appuyez pour réinstaller n'importe quelle version",
        checkForUpdates = "Vérifier les Mises à Jour",
        updatesAvailable = "Mises à Jour Disponibles", guestUser = "Invité",
        installedTitle = "Installé", nothingInstalled = "Rien d'installé pour l'instant",
        nothingInstalledDesc = "Les apps installées via Vyxel\napparaîtront ici",
        installedStatus = "Installé", removedStatus = "Supprimé",
        loadingApps = "Chargement des apps depuis toutes les sources…",
        pressBackToExit = "Appuyez à nouveau pour quitter",
        noApkAvailable = "Pas d'APK Disponible", translateTo = "Traduire en",
    )

    "German" -> AppStrings(
        navHome = "Start", navSearch = "Suchen", navInstalled = "Installiert",
        navProfile = "Profil", navSettings = "Einstellungen",
        searchHint = "GitHub, GitLab, F-Droid durchsuchen…",
        trendingApps = "Angesagte Apps", allSources = "Alle Quellen",
        searching = "Alle Quellen werden durchsucht…",
        fetchingMore = "Weitere Quellen werden abgerufen…",
        noResultsFound = "Keine Ergebnisse gefunden",
        tryDifferent = "Andere Begriffe oder weniger Filter versuchen",
        install = "Installieren", download = "Herunterladen", downloadOnly = "Nur Herunterladen",
        uninstall = "Deinstallieren", cancel = "Abbrechen", save = "Speichern",
        edit = "Bearbeiten", retry = "Erneut versuchen", apply = "Anwenden", refresh = "Aktualisieren",
        back = "Zurück", skipVersion = "Diese Version überspringen",
        checkingRelease = "Neueste Version wird geprüft…",
        stableRelease = "Stabile Version", whatsNew = "Was ist neu",
        noApkFound = "Kein APK in diesem Release gefunden.",
        downloading = "Wird heruntergeladen…",
        stars = "Sterne", forks = "Forks", codingLanguage = "Sprache",
        about = "Über", translate = "Übersetzen", compare = "Vergleichen",
        version = "Version", featured = "EMPFOHLEN", openInBrowser = "Im Browser öffnen",
        updateAvailable = "Update verfügbar", installedBadge = "✓  Installiert",
        screenshots = "Screenshots", release = "Release",
        noDescAvailable = "Keine Beschreibung verfügbar.",
        translatedRedo = "Übersetzt · Wiederholen",
        sectionRecommended = "⭐ Empfohlen für Dich",
        sectionTrending = "🔥 Im Trend", sectionMedia = "🎬 Medien & Unterhaltung",
        sectionTools = "🛠 Werkzeuge", sectionGames = "🎮 Spiele & Emulatoren",
        sectionBrowsers = "🌐 Browser & Datenschutz",
        sectionProductivity = "📋 Produktivität", sectionSecurity = "🔒 Sicherheit",
        sectionDevTools = "💻 Entwicklertools", sectionPhotoVideo = "📸 Foto & Video",
        sectionMusic = "🎵 Musik & Audio", sectionFinance = "💰 Finanzen",
        sectionEducation = "📚 Bildung", sectionFitness = "💪 Fitness & Gesundheit",
        sectionArtDesign = "🎨 Kunst & Design", sectionNews = "🗞 Nachrichten",
        sectionSocial = "💬 Soziales", sectionCloudStorage = "☁️ Cloud-Speicher",
        sectionCooking = "🍳 Kochen & Rezepte",
        settingsTitle = "Einstellungen", appearance = "DARSTELLUNG", themeColor = "THEMENFARBE",
        fontSection = "SCHRIFT", languageSection = "SPRACHE",
        githubSection = "GITHUB", aboutSection = "ÜBER",
        amoledOverride = "AMOLED-Override",
        amoledOverrideDesc = "Reinen schwarzen Hintergrund für alle dunklen Themes erzwingen",
        materialYou = "Material You (Monet)",
        materialYouDesc = "Farben vom Hintergrundbild ableiten",
        personalAccessToken = "Persönliches Zugriffstoken",
        tokenRequired = "Für die GitHub-Suche erforderlich",
        saveToken = "Token speichern", versionLabel = "Version",
        followSystem = "📱  System folgen",
        profileTitle = "Profil", displayName = "Anzeigename", emailAddress = "E-Mail-Adresse",
        supportFeedbackTitle = "Support & Feedback", sendFeedback = "Feedback senden",
        sendFeedbackDesc = "Funktionen vorschlagen oder Fehler melden",
        supportProject = "Projekt unterstützen",
        supportProjectDesc = "Auf GitHub einen Stern geben oder beitragen",
        shareVyxel = "Vyxel teilen", shareVyxelDesc = "Freunden davon erzählen",
        favourites = "Favoriten", recentlyViewed = "Zuletzt angesehen",
        installHistory = "Installationsverlauf",
        installHistoryHint = "Tippen zum Neuinstallieren einer beliebigen Version",
        checkForUpdates = "Nach Updates suchen",
        updatesAvailable = "Updates verfügbar", guestUser = "Gast",
        installedTitle = "Installiert", nothingInstalled = "Noch nichts installiert",
        nothingInstalledDesc = "Apps, die du über Vyxel installierst,\nerscheinen hier",
        installedStatus = "Installiert", removedStatus = "Entfernt",
        loadingApps = "Apps aus allen Quellen werden geladen…",
        pressBackToExit = "Zum Beenden erneut zurück drücken",
        noApkAvailable = "Kein APK verfügbar", translateTo = "Übersetzen nach",
    )

    "Japanese" -> AppStrings(
        navHome = "ホーム", navSearch = "検索", navInstalled = "インストール済",
        navProfile = "プロフィール", navSettings = "設定",
        searchHint = "GitHub、GitLab、F-Droidを検索…",
        trendingApps = "トレンドアプリ", allSources = "全ソース",
        searching = "全ソースを検索中…", fetchingMore = "他のソースから取得中…",
        noResultsFound = "結果が見つかりません",
        tryDifferent = "別のキーワードまたはフィルターを試してください",
        install = "インストール", download = "ダウンロード", downloadOnly = "ダウンロードのみ",
        uninstall = "アンインストール", cancel = "キャンセル", save = "保存",
        edit = "編集", retry = "再試行", apply = "適用", refresh = "更新",
        back = "戻る", skipVersion = "このバージョンをスキップ",
        checkingRelease = "最新リリースを確認中…",
        stableRelease = "安定版リリース", whatsNew = "新着情報",
        noApkFound = "このリリースにAPKが見つかりません。",
        downloading = "ダウンロード中…",
        stars = "スター", forks = "フォーク", codingLanguage = "言語",
        about = "について", translate = "翻訳", compare = "比較",
        version = "バージョン", featured = "注目", openInBrowser = "ブラウザで開く",
        updateAvailable = "アップデートあり", installedBadge = "✓  インストール済",
        screenshots = "スクリーンショット", release = "リリース",
        noDescAvailable = "説明がありません。",
        translatedRedo = "翻訳済 · やり直す",
        sectionRecommended = "⭐ おすすめ",
        sectionTrending = "🔥 急上昇", sectionMedia = "🎬 メディア・エンタメ",
        sectionTools = "🛠 ツール", sectionGames = "🎮 ゲーム・エミュレータ",
        sectionBrowsers = "🌐 ブラウザ・プライバシー",
        sectionProductivity = "📋 生産性", sectionSecurity = "🔒 セキュリティ",
        sectionDevTools = "💻 開発ツール", sectionPhotoVideo = "📸 写真・動画",
        sectionMusic = "🎵 音楽・オーディオ", sectionFinance = "💰 ファイナンス",
        sectionEducation = "📚 教育", sectionFitness = "💪 フィットネス・健康",
        sectionArtDesign = "🎨 アート・デザイン", sectionNews = "🗞 ニュース",
        sectionSocial = "💬 ソーシャル", sectionCloudStorage = "☁️ クラウド",
        sectionCooking = "🍳 料理・レシピ",
        settingsTitle = "設定", appearance = "外観", themeColor = "テーマカラー",
        fontSection = "フォント", languageSection = "言語",
        githubSection = "GITHUB", aboutSection = "アプリについて",
        amoledOverride = "AMOLEDオーバーライド",
        amoledOverrideDesc = "ダークテーマで純粋な黒背景を強制",
        materialYou = "Material You (Monet)",
        materialYouDesc = "壁紙からアクセントカラーを取得",
        personalAccessToken = "個人アクセストークン",
        tokenRequired = "GitHub検索に必要",
        saveToken = "トークンを保存", versionLabel = "バージョン",
        followSystem = "📱  システムに従う",
        profileTitle = "プロフィール", displayName = "表示名", emailAddress = "メールアドレス",
        supportFeedbackTitle = "サポートとフィードバック", sendFeedback = "フィードバックを送信",
        sendFeedbackDesc = "機能の提案やバグ報告",
        supportProject = "プロジェクトをサポート",
        supportProjectDesc = "GitHubでスターを付けるか貢献する",
        shareVyxel = "Vyxelをシェア", shareVyxelDesc = "友達に教える",
        favourites = "お気に入り", recentlyViewed = "最近見た",
        installHistory = "インストール履歴",
        installHistoryHint = "タップしてバージョンを再インストール",
        checkForUpdates = "アップデートを確認", updatesAvailable = "アップデートあり",
        guestUser = "ゲスト",
        installedTitle = "インストール済", nothingInstalled = "まだインストールされていません",
        nothingInstalledDesc = "Vyxelでインストールしたアプリ\nがここに表示されます",
        installedStatus = "インストール済", removedStatus = "削除済",
        loadingApps = "全ソースからアプリを読み込み中…",
        pressBackToExit = "もう一度戻るを押して終了",
        noApkAvailable = "APKなし", translateTo = "に翻訳",
    )

    "Portuguese" -> AppStrings(
        navHome = "Início", navSearch = "Pesquisar", navInstalled = "Instalado",
        navProfile = "Perfil", navSettings = "Configurações",
        searchHint = "Pesquisar no GitHub, GitLab, F-Droid…",
        trendingApps = "Aplicativos em Alta", allSources = "Todas as Fontes",
        searching = "Pesquisando em todas as fontes…",
        fetchingMore = "Buscando em mais fontes…",
        noResultsFound = "Nenhum resultado encontrado",
        tryDifferent = "Tente outros termos ou remova filtros",
        install = "Instalar", download = "Baixar", downloadOnly = "Só Baixar",
        uninstall = "Desinstalar", cancel = "Cancelar", save = "Salvar",
        edit = "Editar", retry = "Tentar Novamente", apply = "Aplicar", refresh = "Atualizar",
        back = "Voltar", skipVersion = "Pular esta versão",
        checkingRelease = "Verificando último lançamento…",
        stableRelease = "Versão estável", whatsNew = "Novidades",
        noApkFound = "Nenhum APK encontrado neste lançamento.",
        downloading = "Baixando…",
        stars = "Estrelas", forks = "Forks", codingLanguage = "Linguagem",
        about = "Sobre", translate = "Traduzir", compare = "Comparar",
        version = "Versão", featured = "DESTAQUE", openInBrowser = "Abrir no Navegador",
        updateAvailable = "Atualização Disponível", installedBadge = "✓  Instalado",
        screenshots = "Capturas de Tela", release = "Lançamento",
        noDescAvailable = "Nenhuma descrição disponível.",
        translatedRedo = "Traduzido · Refazer",
        sectionRecommended = "⭐ Recomendado para Você",
        sectionTrending = "🔥 Em Alta", sectionMedia = "🎬 Mídia e Entretenimento",
        sectionTools = "🛠 Ferramentas", sectionGames = "🎮 Jogos e Emuladores",
        sectionBrowsers = "🌐 Navegadores e Privacidade",
        sectionProductivity = "📋 Produtividade", sectionSecurity = "🔒 Segurança",
        sectionDevTools = "💻 Ferramentas Dev", sectionPhotoVideo = "📸 Foto e Vídeo",
        sectionMusic = "🎵 Música e Áudio", sectionFinance = "💰 Finanças",
        sectionEducation = "📚 Educação", sectionFitness = "💪 Fitness e Saúde",
        sectionArtDesign = "🎨 Arte e Design", sectionNews = "🗞 Notícias",
        sectionSocial = "💬 Social", sectionCloudStorage = "☁️ Armazenamento",
        sectionCooking = "🍳 Culinária e Receitas",
        settingsTitle = "Configurações", appearance = "APARÊNCIA", themeColor = "COR DO TEMA",
        fontSection = "FONTE", languageSection = "IDIOMA",
        githubSection = "GITHUB", aboutSection = "SOBRE",
        amoledOverride = "Override AMOLED",
        amoledOverrideDesc = "Forçar fundo preto puro em qualquer tema escuro",
        materialYou = "Material You (Monet)",
        materialYouDesc = "Obtém cores do seu papel de parede",
        personalAccessToken = "Token de Acesso Pessoal",
        tokenRequired = "Necessário para busca no GitHub",
        saveToken = "Salvar Token", versionLabel = "Versão",
        followSystem = "📱  Seguir Sistema",
        profileTitle = "Perfil", displayName = "Nome de exibição", emailAddress = "Endereço de e-mail",
        supportFeedbackTitle = "Suporte e Feedback", sendFeedback = "Enviar Feedback",
        sendFeedbackDesc = "Sugerir recursos ou reportar bugs",
        supportProject = "Apoiar o Projeto",
        supportProjectDesc = "Dar estrela no GitHub ou contribuir",
        shareVyxel = "Compartilhar Vyxel", shareVyxelDesc = "Conte aos seus amigos",
        favourites = "Favoritos", recentlyViewed = "Vistos Recentemente",
        installHistory = "Histórico de Instalação",
        installHistoryHint = "Toque para reinstalar qualquer versão",
        checkForUpdates = "Verificar Atualizações",
        updatesAvailable = "Atualizações Disponíveis", guestUser = "Convidado",
        installedTitle = "Instalado", nothingInstalled = "Nada instalado ainda",
        nothingInstalledDesc = "Apps instalados pelo Vyxel\naparecerão aqui",
        installedStatus = "Instalado", removedStatus = "Removido",
        loadingApps = "Carregando apps de todas as fontes…",
        pressBackToExit = "Pressione voltar novamente para sair",
        noApkAvailable = "Sem APK Disponível", translateTo = "Traduzir para",
    )

    "Italian" -> AppStrings(
        navHome = "Home", navSearch = "Cerca", navInstalled = "Installato",
        navProfile = "Profilo", navSettings = "Impostazioni",
        searchHint = "Cerca su GitHub, GitLab, F-Droid…",
        trendingApps = "App di Tendenza", allSources = "Tutte le Fonti",
        searching = "Ricerca in tutte le fonti…",
        fetchingMore = "Recupero da altre fonti…",
        noResultsFound = "Nessun risultato trovato",
        tryDifferent = "Prova termini diversi o rimuovi filtri",
        install = "Installa", download = "Scarica", downloadOnly = "Solo Scarica",
        uninstall = "Disinstalla", cancel = "Annulla", save = "Salva",
        edit = "Modifica", retry = "Riprova", apply = "Applica", refresh = "Aggiorna",
        back = "Indietro", skipVersion = "Salta questa versione",
        checkingRelease = "Controllo ultima versione…",
        stableRelease = "Versione stabile", whatsNew = "Novità",
        noApkFound = "Nessun APK trovato in questa versione.",
        downloading = "Download in corso…",
        stars = "Stelle", forks = "Fork", codingLanguage = "Linguaggio",
        about = "Informazioni", translate = "Traduci", compare = "Confronta",
        version = "Versione", featured = "IN EVIDENZA", openInBrowser = "Apri nel Browser",
        updateAvailable = "Aggiornamento Disponibile", installedBadge = "✓  Installato",
        screenshots = "Schermate", release = "Rilascio",
        noDescAvailable = "Nessuna descrizione disponibile.",
        translatedRedo = "Tradotto · Rifare",
        sectionRecommended = "⭐ Raccomandato per Te",
        sectionTrending = "🔥 Tendenze", sectionMedia = "🎬 Media e Intrattenimento",
        sectionTools = "🛠 Strumenti", sectionGames = "🎮 Giochi ed Emulatori",
        sectionBrowsers = "🌐 Browser e Privacy",
        sectionProductivity = "📋 Produttività", sectionSecurity = "🔒 Sicurezza",
        sectionDevTools = "💻 Strumenti Dev", sectionPhotoVideo = "📸 Foto e Video",
        sectionMusic = "🎵 Musica e Audio", sectionFinance = "💰 Finanza",
        sectionEducation = "📚 Istruzione", sectionFitness = "💪 Fitness e Salute",
        sectionArtDesign = "🎨 Arte e Design", sectionNews = "🗞 Notizie",
        sectionSocial = "💬 Social", sectionCloudStorage = "☁️ Archiviazione Cloud",
        sectionCooking = "🍳 Cucina e Ricette",
        settingsTitle = "Impostazioni", appearance = "ASPETTO", themeColor = "COLORE TEMA",
        fontSection = "CARATTERE", languageSection = "LINGUA",
        githubSection = "GITHUB", aboutSection = "INFORMAZIONI",
        amoledOverride = "Override AMOLED",
        amoledOverrideDesc = "Forza sfondo nero puro su qualsiasi tema scuro",
        materialYou = "Material You (Monet)",
        materialYouDesc = "Deriva i colori dal tuo sfondo",
        personalAccessToken = "Token di Accesso Personale",
        tokenRequired = "Necessario per la ricerca su GitHub",
        saveToken = "Salva Token", versionLabel = "Versione",
        followSystem = "📱  Segui Sistema",
        profileTitle = "Profilo", displayName = "Nome visualizzato", emailAddress = "Indirizzo email",
        supportFeedbackTitle = "Supporto e Feedback", sendFeedback = "Invia Feedback",
        sendFeedbackDesc = "Suggerisci funzionalità o segnala bug",
        supportProject = "Supporta il Progetto",
        supportProjectDesc = "Metti una stella su GitHub o contribuisci",
        shareVyxel = "Condividi Vyxel", shareVyxelDesc = "Dillo ai tuoi amici",
        favourites = "Preferiti", recentlyViewed = "Visualizzati di Recente",
        installHistory = "Cronologia Installazioni",
        installHistoryHint = "Tocca per reinstallare qualsiasi versione",
        checkForUpdates = "Verifica Aggiornamenti",
        updatesAvailable = "Aggiornamenti Disponibili", guestUser = "Ospite",
        installedTitle = "Installato", nothingInstalled = "Niente installato ancora",
        nothingInstalledDesc = "Le app installate tramite Vyxel\nappariranno qui",
        installedStatus = "Installato", removedStatus = "Rimosso",
        loadingApps = "Caricamento app da tutte le fonti…",
        pressBackToExit = "Premi di nuovo indietro per uscire",
        noApkAvailable = "Nessun APK Disponibile", translateTo = "Traduci in",
    )

    "Russian" -> AppStrings(
        navHome = "Главная", navSearch = "Поиск", navInstalled = "Установлено",
        navProfile = "Профиль", navSettings = "Настройки",
        searchHint = "Поиск в GitHub, GitLab, F-Droid…",
        trendingApps = "Популярные приложения", allSources = "Все источники",
        searching = "Поиск во всех источниках…",
        fetchingMore = "Загрузка из других источников…",
        noResultsFound = "Результаты не найдены",
        tryDifferent = "Попробуйте другие слова или уберите фильтры",
        install = "Установить", download = "Скачать", downloadOnly = "Только скачать",
        uninstall = "Удалить", cancel = "Отмена", save = "Сохранить",
        edit = "Редактировать", retry = "Повторить", apply = "Применить", refresh = "Обновить",
        back = "Назад", skipVersion = "Пропустить версию",
        checkingRelease = "Проверка последнего релиза…",
        stableRelease = "Стабильная версия", whatsNew = "Что нового",
        noApkFound = "APK не найден в этом релизе.",
        downloading = "Загрузка…",
        stars = "Звёзды", forks = "Форки", codingLanguage = "Язык",
        about = "О программе", translate = "Перевести", compare = "Сравнить",
        version = "Версия", featured = "РЕКОМЕНДУЕМ", openInBrowser = "Открыть в браузере",
        updateAvailable = "Доступно обновление", installedBadge = "✓  Установлено",
        screenshots = "Скриншоты", release = "Релиз",
        noDescAvailable = "Описание недоступно.",
        translatedRedo = "Переведено · Повторить",
        sectionRecommended = "⭐ Рекомендуем для Вас",
        sectionTrending = "🔥 В тренде", sectionMedia = "🎬 Медиа и развлечения",
        sectionTools = "🛠 Инструменты", sectionGames = "🎮 Игры и эмуляторы",
        sectionBrowsers = "🌐 Браузеры и конфиденциальность",
        sectionProductivity = "📋 Продуктивность", sectionSecurity = "🔒 Безопасность",
        sectionDevTools = "💻 Инструменты разработчика", sectionPhotoVideo = "📸 Фото и видео",
        sectionMusic = "🎵 Музыка и аудио", sectionFinance = "💰 Финансы",
        sectionEducation = "📚 Образование", sectionFitness = "💪 Фитнес и здоровье",
        sectionArtDesign = "🎨 Искусство и дизайн", sectionNews = "🗞 Новости",
        sectionSocial = "💬 Социальные сети", sectionCloudStorage = "☁️ Облачное хранилище",
        sectionCooking = "🍳 Кулинария и рецепты",
        settingsTitle = "Настройки", appearance = "ВНЕШНИЙ ВИД", themeColor = "ЦВЕТ ТЕМЫ",
        fontSection = "ШРИФТ", languageSection = "ЯЗЫК",
        githubSection = "GITHUB", aboutSection = "О ПРОГРАММЕ",
        amoledOverride = "AMOLED-переопределение",
        amoledOverrideDesc = "Чисто чёрный фон для любой тёмной темы",
        materialYou = "Material You (Monet)",
        materialYouDesc = "Получает цвета из обоев",
        personalAccessToken = "Персональный токен доступа",
        tokenRequired = "Необходим для поиска в GitHub",
        saveToken = "Сохранить токен", versionLabel = "Версия",
        followSystem = "📱  Следовать системе",
        profileTitle = "Профиль", displayName = "Имя", emailAddress = "Электронная почта",
        supportFeedbackTitle = "Поддержка и отзывы", sendFeedback = "Отправить отзыв",
        sendFeedbackDesc = "Предложить функции или сообщить об ошибке",
        supportProject = "Поддержать проект",
        supportProjectDesc = "Поставить звезду на GitHub или участвовать",
        shareVyxel = "Поделиться Vyxel", shareVyxelDesc = "Расскажи друзьям",
        favourites = "Избранное", recentlyViewed = "Недавно просмотренные",
        installHistory = "История установок",
        installHistoryHint = "Нажмите для переустановки версии",
        checkForUpdates = "Проверить обновления",
        updatesAvailable = "Доступны обновления", guestUser = "Гость",
        installedTitle = "Установлено", nothingInstalled = "Ничего не установлено",
        nothingInstalledDesc = "Приложения, установленные через Vyxel,\nбудут здесь",
        installedStatus = "Установлено", removedStatus = "Удалено",
        loadingApps = "Загрузка приложений из всех источников…",
        pressBackToExit = "Нажмите ещё раз для выхода",
        noApkAvailable = "APK недоступен", translateTo = "Перевести на",
    )

    "Chinese" -> AppStrings(
        navHome = "主页", navSearch = "搜索", navInstalled = "已安装",
        navProfile = "个人资料", navSettings = "设置",
        searchHint = "搜索 GitHub、GitLab、F-Droid…",
        trendingApps = "热门应用", allSources = "所有来源",
        searching = "正在搜索所有来源…", fetchingMore = "从更多来源获取中…",
        noResultsFound = "未找到结果",
        tryDifferent = "尝试不同的搜索词或删除筛选器",
        install = "安装", download = "下载", downloadOnly = "仅下载",
        uninstall = "卸载", cancel = "取消", save = "保存",
        edit = "编辑", retry = "重试", apply = "应用", refresh = "刷新",
        back = "返回", skipVersion = "跳过此版本",
        checkingRelease = "正在检查最新版本…",
        stableRelease = "稳定版", whatsNew = "更新内容",
        noApkFound = "此版本中未找到 APK。",
        downloading = "下载中…",
        stars = "星标", forks = "分叉", codingLanguage = "语言",
        about = "关于", translate = "翻译", compare = "比较",
        version = "版本", featured = "精选", openInBrowser = "在浏览器中打开",
        updateAvailable = "有可用更新", installedBadge = "✓  已安装",
        screenshots = "截图", release = "发布",
        noDescAvailable = "暂无描述。",
        translatedRedo = "已翻译 · 重新翻译",
        sectionRecommended = "⭐ 为您推荐",
        sectionTrending = "🔥 正在流行", sectionMedia = "🎬 媒体与娱乐",
        sectionTools = "🛠 工具", sectionGames = "🎮 游戏与模拟器",
        sectionBrowsers = "🌐 浏览器与隐私",
        sectionProductivity = "📋 生产力", sectionSecurity = "🔒 安全",
        sectionDevTools = "💻 开发工具", sectionPhotoVideo = "📸 照片与视频",
        sectionMusic = "🎵 音乐与音频", sectionFinance = "💰 金融",
        sectionEducation = "📚 教育", sectionFitness = "💪 健身与健康",
        sectionArtDesign = "🎨 艺术与设计", sectionNews = "🗞 新闻",
        sectionSocial = "💬 社交", sectionCloudStorage = "☁️ 云存储",
        sectionCooking = "🍳 烹饪与食谱",
        settingsTitle = "设置", appearance = "外观", themeColor = "主题颜色",
        fontSection = "字体", languageSection = "语言",
        githubSection = "GITHUB", aboutSection = "关于",
        amoledOverride = "AMOLED 覆盖",
        amoledOverrideDesc = "在任何深色主题上强制使用纯黑背景",
        materialYou = "Material You (Monet)",
        materialYouDesc = "从壁纸中提取强调色和色调",
        personalAccessToken = "个人访问令牌",
        tokenRequired = "GitHub 搜索所需",
        saveToken = "保存令牌", versionLabel = "版本",
        followSystem = "📱  跟随系统",
        profileTitle = "个人资料", displayName = "显示名称", emailAddress = "电子邮件地址",
        supportFeedbackTitle = "支持与反馈", sendFeedback = "发送反馈",
        sendFeedbackDesc = "建议功能或报告错误",
        supportProject = "支持项目",
        supportProjectDesc = "在 GitHub 上点赞或贡献",
        shareVyxel = "分享 Vyxel", shareVyxelDesc = "告诉你的朋友",
        favourites = "收藏", recentlyViewed = "最近查看",
        installHistory = "安装历史",
        installHistoryHint = "点击重新安装任何版本",
        checkForUpdates = "检查更新",
        updatesAvailable = "有可用更新", guestUser = "访客",
        installedTitle = "已安装", nothingInstalled = "尚未安装任何内容",
        nothingInstalledDesc = "通过 Vyxel 安装的应用\n将显示在此处",
        installedStatus = "已安装", removedStatus = "已移除",
        loadingApps = "正在从所有来源加载应用…",
        pressBackToExit = "再次按返回键退出",
        noApkAvailable = "无可用 APK", translateTo = "翻译为",
    )

    "Korean" -> AppStrings(
        navHome = "홈", navSearch = "검색", navInstalled = "설치됨",
        navProfile = "프로필", navSettings = "설정",
        searchHint = "GitHub, GitLab, F-Droid 검색…",
        trendingApps = "인기 앱", allSources = "전체 소스",
        searching = "모든 소스에서 검색 중…", fetchingMore = "더 많은 소스에서 가져오는 중…",
        noResultsFound = "결과를 찾을 수 없습니다",
        tryDifferent = "다른 검색어나 필터를 사용해 보세요",
        install = "설치", download = "다운로드", downloadOnly = "다운로드만",
        uninstall = "제거", cancel = "취소", save = "저장",
        edit = "편집", retry = "다시 시도", apply = "적용", refresh = "새로고침",
        back = "뒤로", skipVersion = "이 버전 건너뛰기",
        checkingRelease = "최신 릴리스 확인 중…",
        stableRelease = "안정 버전", whatsNew = "새 기능",
        noApkFound = "이 릴리스에 APK가 없습니다.",
        downloading = "다운로드 중…",
        stars = "스타", forks = "포크", codingLanguage = "언어",
        about = "정보", translate = "번역", compare = "비교",
        version = "버전", featured = "추천", openInBrowser = "브라우저에서 열기",
        updateAvailable = "업데이트 사용 가능", installedBadge = "✓  설치됨",
        screenshots = "스크린샷", release = "릴리스",
        noDescAvailable = "설명이 없습니다.",
        translatedRedo = "번역됨 · 다시 하기",
        sectionRecommended = "⭐ 추천 앱",
        sectionTrending = "🔥 지금 인기", sectionMedia = "🎬 미디어 & 엔터테인먼트",
        sectionTools = "🛠 도구", sectionGames = "🎮 게임 & 에뮬레이터",
        sectionBrowsers = "🌐 브라우저 & 개인정보",
        sectionProductivity = "📋 생산성", sectionSecurity = "🔒 보안",
        sectionDevTools = "💻 개발 도구", sectionPhotoVideo = "📸 사진 & 동영상",
        sectionMusic = "🎵 음악 & 오디오", sectionFinance = "💰 금융",
        sectionEducation = "📚 교육", sectionFitness = "💪 피트니스 & 건강",
        sectionArtDesign = "🎨 아트 & 디자인", sectionNews = "🗞 뉴스",
        sectionSocial = "💬 소셜", sectionCloudStorage = "☁️ 클라우드 저장소",
        sectionCooking = "🍳 요리 & 레시피",
        settingsTitle = "설정", appearance = "외관", themeColor = "테마 색상",
        fontSection = "폰트", languageSection = "언어",
        githubSection = "GITHUB", aboutSection = "앱 정보",
        amoledOverride = "AMOLED 오버라이드",
        amoledOverrideDesc = "다크 테마에서 순수 검정 배경 강제 적용",
        materialYou = "Material You (Monet)",
        materialYouDesc = "배경화면에서 강조색 추출",
        personalAccessToken = "개인 액세스 토큰",
        tokenRequired = "GitHub 검색에 필요",
        saveToken = "토큰 저장", versionLabel = "버전",
        followSystem = "📱  시스템 따르기",
        profileTitle = "프로필", displayName = "표시 이름", emailAddress = "이메일 주소",
        supportFeedbackTitle = "지원 & 피드백", sendFeedback = "피드백 보내기",
        sendFeedbackDesc = "기능 제안 또는 버그 보고",
        supportProject = "프로젝트 지원",
        supportProjectDesc = "GitHub에서 별표 또는 기여",
        shareVyxel = "Vyxel 공유", shareVyxelDesc = "친구에게 알려주세요",
        favourites = "즐겨찾기", recentlyViewed = "최근 본 항목",
        installHistory = "설치 기록",
        installHistoryHint = "탭하여 버전 재설치",
        checkForUpdates = "업데이트 확인",
        updatesAvailable = "업데이트 가능", guestUser = "게스트",
        installedTitle = "설치됨", nothingInstalled = "설치된 항목 없음",
        nothingInstalledDesc = "Vyxel로 설치한 앱이\n여기에 표시됩니다",
        installedStatus = "설치됨", removedStatus = "제거됨",
        loadingApps = "모든 소스에서 앱 로드 중…",
        pressBackToExit = "다시 뒤로 누르면 종료",
        noApkAvailable = "APK 없음", translateTo = "번역 언어",
    )

    "Arabic" -> AppStrings(
        navHome = "الرئيسية", navSearch = "بحث", navInstalled = "مثبّت",
        navProfile = "الملف", navSettings = "الإعدادات",
        searchHint = "البحث في GitHub وGitLab وF-Droid…",
        trendingApps = "التطبيقات الرائجة", allSources = "جميع المصادر",
        searching = "جارٍ البحث في جميع المصادر…",
        fetchingMore = "جارٍ الجلب من مصادر أخرى…",
        noResultsFound = "لم يتم العثور على نتائج",
        tryDifferent = "جرّب مصطلحات مختلفة أو أزِل بعض المرشحات",
        install = "تثبيت", download = "تحميل", downloadOnly = "التحميل فقط",
        uninstall = "إلغاء التثبيت", cancel = "إلغاء", save = "حفظ",
        edit = "تعديل", retry = "إعادة المحاولة", apply = "تطبيق", refresh = "تحديث",
        back = "رجوع", skipVersion = "تخطّي هذا الإصدار",
        checkingRelease = "جارٍ التحقق من أحدث إصدار…",
        stableRelease = "إصدار مستقر", whatsNew = "ما الجديد",
        noApkFound = "لم يُعثر على APK في هذا الإصدار.",
        downloading = "جارٍ التحميل…",
        stars = "نجوم", forks = "فروع", codingLanguage = "اللغة",
        about = "حول", translate = "ترجمة", compare = "مقارنة",
        version = "الإصدار", featured = "مميّز", openInBrowser = "فتح في المتصفح",
        updateAvailable = "تحديث متاح", installedBadge = "✓  مثبّت",
        screenshots = "لقطات الشاشة", release = "الإصدار",
        noDescAvailable = "لا يوجد وصف.",
        translatedRedo = "مترجم · إعادة الترجمة",
        sectionRecommended = "⭐ موصى به لك",
        sectionTrending = "🔥 رائج الآن", sectionMedia = "🎬 الوسائط والترفيه",
        sectionTools = "🛠 الأدوات", sectionGames = "🎮 الألعاب والمحاكيات",
        sectionBrowsers = "🌐 المتصفحات والخصوصية",
        sectionProductivity = "📋 الإنتاجية", sectionSecurity = "🔒 الأمن",
        sectionDevTools = "💻 أدوات المطورين", sectionPhotoVideo = "📸 الصور والفيديو",
        sectionMusic = "🎵 الموسيقى والصوت", sectionFinance = "💰 المالية",
        sectionEducation = "📚 التعليم", sectionFitness = "💪 اللياقة والصحة",
        sectionArtDesign = "🎨 الفن والتصميم", sectionNews = "🗞 الأخبار",
        sectionSocial = "💬 الاجتماعي", sectionCloudStorage = "☁️ التخزين السحابي",
        sectionCooking = "🍳 الطبخ والوصفات",
        settingsTitle = "الإعدادات", appearance = "المظهر", themeColor = "لون السمة",
        fontSection = "الخط", languageSection = "اللغة",
        githubSection = "GITHUB", aboutSection = "حول",
        amoledOverride = "تجاوز AMOLED",
        amoledOverrideDesc = "فرض خلفية سوداء خالصة على أي سمة داكنة",
        materialYou = "Material You (Monet)",
        materialYouDesc = "يستخرج الألوان من خلفية شاشتك",
        personalAccessToken = "رمز الوصول الشخصي",
        tokenRequired = "مطلوب للبحث في GitHub",
        saveToken = "حفظ الرمز", versionLabel = "الإصدار",
        followSystem = "📱  اتباع النظام",
        profileTitle = "الملف الشخصي", displayName = "الاسم المعروض", emailAddress = "البريد الإلكتروني",
        supportFeedbackTitle = "الدعم والملاحظات", sendFeedback = "إرسال ملاحظات",
        sendFeedbackDesc = "اقتراح ميزات أو الإبلاغ عن أخطاء",
        supportProject = "دعم المشروع",
        supportProjectDesc = "ضع نجمة على GitHub أو ساهم",
        shareVyxel = "مشاركة Vyxel", shareVyxelDesc = "أخبر أصدقاءك",
        favourites = "المفضلة", recentlyViewed = "شوهد مؤخراً",
        installHistory = "سجل التثبيت",
        installHistoryHint = "انقر لإعادة تثبيت أي إصدار",
        checkForUpdates = "التحقق من التحديثات",
        updatesAvailable = "تحديثات متاحة", guestUser = "ضيف",
        installedTitle = "مثبّت", nothingInstalled = "لم يُثبَّت شيء بعد",
        nothingInstalledDesc = "ستظهر هنا التطبيقات\nالتي تُثبّتها عبر Vyxel",
        installedStatus = "مثبّت", removedStatus = "مُزال",
        loadingApps = "جارٍ تحميل التطبيقات من جميع المصادر…",
        pressBackToExit = "اضغط رجوع مرة أخرى للخروج",
        noApkAvailable = "لا يوجد APK", translateTo = "ترجمة إلى",
    )

    "Dutch" -> AppStrings(
        navHome = "Home", navSearch = "Zoeken", navInstalled = "Geïnstalleerd",
        navProfile = "Profiel", navSettings = "Instellingen",
        searchHint = "Zoeken in GitHub, GitLab, F-Droid…",
        trendingApps = "Populaire Apps", allSources = "Alle Bronnen",
        searching = "Zoeken in alle bronnen…", fetchingMore = "Ophalen van meer bronnen…",
        noResultsFound = "Geen resultaten gevonden",
        tryDifferent = "Probeer andere termen of verwijder filters",
        install = "Installeren", download = "Downloaden", downloadOnly = "Alleen Downloaden",
        uninstall = "Verwijderen", cancel = "Annuleren", save = "Opslaan",
        edit = "Bewerken", retry = "Opnieuw proberen", apply = "Toepassen", refresh = "Vernieuwen",
        back = "Terug", skipVersion = "Deze versie overslaan",
        checkingRelease = "Laatste release controleren…",
        stableRelease = "Stabiele versie", whatsNew = "Nieuw",
        noApkFound = "Geen APK gevonden in deze release.",
        downloading = "Downloaden…",
        stars = "Sterren", forks = "Forks", codingLanguage = "Taal",
        about = "Over", translate = "Vertalen", compare = "Vergelijken",
        version = "Versie", featured = "UITGELICHT", openInBrowser = "Openen in Browser",
        updateAvailable = "Update Beschikbaar", installedBadge = "✓  Geïnstalleerd",
        screenshots = "Screenshots", release = "Release",
        noDescAvailable = "Geen beschrijving beschikbaar.",
        translatedRedo = "Vertaald · Opnieuw",
        sectionRecommended = "⭐ Aanbevolen voor Jou",
        sectionTrending = "🔥 Trending", sectionMedia = "🎬 Media & Entertainment",
        sectionTools = "🛠 Tools", sectionGames = "🎮 Games & Emulators",
        sectionBrowsers = "🌐 Browsers & Privacy",
        sectionProductivity = "📋 Productiviteit", sectionSecurity = "🔒 Beveiliging",
        sectionDevTools = "💻 Dev Tools", sectionPhotoVideo = "📸 Foto & Video",
        sectionMusic = "🎵 Muziek & Audio", sectionFinance = "💰 Financiën",
        sectionEducation = "📚 Onderwijs", sectionFitness = "💪 Fitness & Gezondheid",
        sectionArtDesign = "🎨 Kunst & Design", sectionNews = "🗞 Nieuws",
        sectionSocial = "💬 Sociaal", sectionCloudStorage = "☁️ Cloudopslag",
        sectionCooking = "🍳 Koken & Recepten",
        settingsTitle = "Instellingen", appearance = "UITERLIJK", themeColor = "THEMAKLEUR",
        fontSection = "LETTERTYPE", languageSection = "TAAL",
        githubSection = "GITHUB", aboutSection = "OVER",
        amoledOverride = "AMOLED-override",
        amoledOverrideDesc = "Puur zwarte achtergrond op elk donker thema",
        materialYou = "Material You (Monet)",
        materialYouDesc = "Haalt kleuren uit je achtergrond",
        personalAccessToken = "Persoonlijk Toegangstoken",
        tokenRequired = "Vereist voor GitHub-zoeken",
        saveToken = "Token Opslaan", versionLabel = "Versie",
        followSystem = "📱  Systeem volgen",
        profileTitle = "Profiel", displayName = "Weergavenaam", emailAddress = "E-mailadres",
        supportFeedbackTitle = "Ondersteuning & Feedback", sendFeedback = "Feedback Sturen",
        sendFeedbackDesc = "Functies voorstellen of bugs melden",
        supportProject = "Project Ondersteunen",
        supportProjectDesc = "Ster geven op GitHub of bijdragen",
        shareVyxel = "Vyxel Delen", shareVyxelDesc = "Vertel het je vrienden",
        favourites = "Favorieten", recentlyViewed = "Recent Bekeken",
        installHistory = "Installatiegeschiedenis",
        installHistoryHint = "Tik om een versie opnieuw te installeren",
        checkForUpdates = "Controleren op Updates",
        updatesAvailable = "Updates Beschikbaar", guestUser = "Gast",
        installedTitle = "Geïnstalleerd", nothingInstalled = "Nog niets geïnstalleerd",
        nothingInstalledDesc = "Apps die je via Vyxel installeert\nverschijnen hier",
        installedStatus = "Geïnstalleerd", removedStatus = "Verwijderd",
        loadingApps = "Apps laden van alle bronnen…",
        pressBackToExit = "Druk nogmaals terug om te sluiten",
        noApkAvailable = "Geen APK Beschikbaar", translateTo = "Vertalen naar",
    )

    "Turkish" -> AppStrings(
        navHome = "Ana Sayfa", navSearch = "Ara", navInstalled = "Kurulu",
        navProfile = "Profil", navSettings = "Ayarlar",
        searchHint = "GitHub, GitLab, F-Droid'de ara…",
        trendingApps = "Popüler Uygulamalar", allSources = "Tüm Kaynaklar",
        searching = "Tüm kaynaklarda aranıyor…", fetchingMore = "Daha fazla kaynaktan alınıyor…",
        noResultsFound = "Sonuç bulunamadı",
        tryDifferent = "Farklı terimler veya daha az filtre deneyin",
        install = "Yükle", download = "İndir", downloadOnly = "Sadece İndir",
        uninstall = "Kaldır", cancel = "İptal", save = "Kaydet",
        edit = "Düzenle", retry = "Yeniden Dene", apply = "Uygula", refresh = "Yenile",
        back = "Geri", skipVersion = "Bu sürümü atla",
        checkingRelease = "Son sürüm kontrol ediliyor…",
        stableRelease = "Kararlı sürüm", whatsNew = "Yenilikler",
        noApkFound = "Bu sürümde APK bulunamadı.",
        downloading = "İndiriliyor…",
        stars = "Yıldız", forks = "Çatallar", codingLanguage = "Dil",
        about = "Hakkında", translate = "Çevir", compare = "Karşılaştır",
        version = "Sürüm", featured = "ÖNE ÇIKAN", openInBrowser = "Tarayıcıda Aç",
        updateAvailable = "Güncelleme Mevcut", installedBadge = "✓  Kurulu",
        screenshots = "Ekran Görüntüleri", release = "Sürüm",
        noDescAvailable = "Açıklama yok.",
        translatedRedo = "Çevrildi · Yeniden Yap",
        sectionRecommended = "⭐ Senin İçin Önerilen",
        sectionTrending = "🔥 Trend", sectionMedia = "🎬 Medya & Eğlence",
        sectionTools = "🛠 Araçlar", sectionGames = "🎮 Oyunlar & Emülatörler",
        sectionBrowsers = "🌐 Tarayıcılar & Gizlilik",
        sectionProductivity = "📋 Verimlilik", sectionSecurity = "🔒 Güvenlik",
        sectionDevTools = "💻 Geliştirici Araçları", sectionPhotoVideo = "📸 Fotoğraf & Video",
        sectionMusic = "🎵 Müzik & Ses", sectionFinance = "💰 Finans",
        sectionEducation = "📚 Eğitim", sectionFitness = "💪 Fitness & Sağlık",
        sectionArtDesign = "🎨 Sanat & Tasarım", sectionNews = "🗞 Haberler",
        sectionSocial = "💬 Sosyal", sectionCloudStorage = "☁️ Bulut Depolama",
        sectionCooking = "🍳 Yemek & Tarifler",
        settingsTitle = "Ayarlar", appearance = "GÖRÜNÜM", themeColor = "TEMA RENGİ",
        fontSection = "YAZI TİPİ", languageSection = "DİL",
        githubSection = "GITHUB", aboutSection = "HAKKINDA",
        amoledOverride = "AMOLED Override",
        amoledOverrideDesc = "Herhangi bir koyu temada saf siyah arka plan",
        materialYou = "Material You (Monet)",
        materialYouDesc = "Duvar kağıdından renkleri alır",
        personalAccessToken = "Kişisel Erişim Jetonu",
        tokenRequired = "GitHub araması için gerekli",
        saveToken = "Jetonu Kaydet", versionLabel = "Sürüm",
        followSystem = "📱  Sistemi Takip Et",
        profileTitle = "Profil", displayName = "Görünen ad", emailAddress = "E-posta adresi",
        supportFeedbackTitle = "Destek & Geri Bildirim", sendFeedback = "Geri Bildirim Gönder",
        sendFeedbackDesc = "Özellik öner veya hata bildir",
        supportProject = "Projeyi Destekle",
        supportProjectDesc = "GitHub'da yıldız ver veya katkıda bulun",
        shareVyxel = "Vyxel'i Paylaş", shareVyxelDesc = "Arkadaşlarına anlat",
        favourites = "Favoriler", recentlyViewed = "Son Görüntülenen",
        installHistory = "Kurulum Geçmişi",
        installHistoryHint = "Yeniden yüklemek için dokunun",
        checkForUpdates = "Güncelleme Kontrol Et",
        updatesAvailable = "Güncellemeler Mevcut", guestUser = "Misafir",
        installedTitle = "Kurulu", nothingInstalled = "Henüz bir şey kurulmadı",
        nothingInstalledDesc = "Vyxel aracılığıyla kurduğun uygulamalar\nburada görünecek",
        installedStatus = "Kurulu", removedStatus = "Kaldırıldı",
        loadingApps = "Tüm kaynaklardan uygulamalar yükleniyor…",
        pressBackToExit = "Çıkmak için tekrar geri basın",
        noApkAvailable = "APK Mevcut Değil", translateTo = "Çevir:",
    )

    "Polish" -> AppStrings(
        navHome = "Główna", navSearch = "Szukaj", navInstalled = "Zainstalowane",
        navProfile = "Profil", navSettings = "Ustawienia",
        searchHint = "Szukaj w GitHub, GitLab, F-Droid…",
        trendingApps = "Popularne Aplikacje", allSources = "Wszystkie Źródła",
        searching = "Przeszukiwanie wszystkich źródeł…",
        fetchingMore = "Pobieranie z kolejnych źródeł…",
        noResultsFound = "Nie znaleziono wyników",
        tryDifferent = "Spróbuj innych słów lub usuń filtry",
        install = "Zainstaluj", download = "Pobierz", downloadOnly = "Tylko Pobierz",
        uninstall = "Odinstaluj", cancel = "Anuluj", save = "Zapisz",
        edit = "Edytuj", retry = "Spróbuj ponownie", apply = "Zastosuj", refresh = "Odśwież",
        back = "Wstecz", skipVersion = "Pomiń tę wersję",
        checkingRelease = "Sprawdzanie najnowszego wydania…",
        stableRelease = "Wersja stabilna", whatsNew = "Co nowego",
        noApkFound = "W tym wydaniu nie znaleziono APK.",
        downloading = "Pobieranie…",
        stars = "Gwiazdki", forks = "Forki", codingLanguage = "Język",
        about = "O aplikacji", translate = "Przetłumacz", compare = "Porównaj",
        version = "Wersja", featured = "WYRÓŻNIONE", openInBrowser = "Otwórz w Przeglądarce",
        updateAvailable = "Aktualizacja Dostępna", installedBadge = "✓  Zainstalowane",
        screenshots = "Zrzuty ekranu", release = "Wydanie",
        noDescAvailable = "Brak opisu.",
        translatedRedo = "Przetłumaczono · Powtórz",
        sectionRecommended = "⭐ Polecane dla Ciebie",
        sectionTrending = "🔥 Trendy", sectionMedia = "🎬 Media i Rozrywka",
        sectionTools = "🛠 Narzędzia", sectionGames = "🎮 Gry i Emulatory",
        sectionBrowsers = "🌐 Przeglądarki i Prywatność",
        sectionProductivity = "📋 Produktywność", sectionSecurity = "🔒 Bezpieczeństwo",
        sectionDevTools = "💻 Narzędzia Dev", sectionPhotoVideo = "📸 Zdjęcia i Wideo",
        sectionMusic = "🎵 Muzyka i Audio", sectionFinance = "💰 Finanse",
        sectionEducation = "📚 Edukacja", sectionFitness = "💪 Fitness i Zdrowie",
        sectionArtDesign = "🎨 Sztuka i Design", sectionNews = "🗞 Wiadomości",
        sectionSocial = "💬 Społeczność", sectionCloudStorage = "☁️ Chmura",
        sectionCooking = "🍳 Gotowanie i Przepisy",
        settingsTitle = "Ustawienia", appearance = "WYGLĄD", themeColor = "KOLOR MOTYWU",
        fontSection = "CZCIONKA", languageSection = "JĘZYK",
        githubSection = "GITHUB", aboutSection = "O APLIKACJI",
        amoledOverride = "Nadpisanie AMOLED",
        amoledOverrideDesc = "Czarne tło na każdym ciemnym motywie",
        materialYou = "Material You (Monet)",
        materialYouDesc = "Pobiera kolory z tapety",
        personalAccessToken = "Osobisty Token Dostępu",
        tokenRequired = "Wymagany do wyszukiwania w GitHub",
        saveToken = "Zapisz Token", versionLabel = "Wersja",
        followSystem = "📱  Śledź System",
        profileTitle = "Profil", displayName = "Nazwa wyświetlana", emailAddress = "Adres email",
        supportFeedbackTitle = "Wsparcie i Opinie", sendFeedback = "Wyślij Opinię",
        sendFeedbackDesc = "Zaproponuj funkcje lub zgłoś błędy",
        supportProject = "Wesprzyj Projekt",
        supportProjectDesc = "Daj gwiazdkę na GitHub lub weź udział",
        shareVyxel = "Udostępnij Vyxel", shareVyxelDesc = "Powiedz znajomym",
        favourites = "Ulubione", recentlyViewed = "Ostatnio Przeglądane",
        installHistory = "Historia Instalacji",
        installHistoryHint = "Dotknij, aby ponownie zainstalować wersję",
        checkForUpdates = "Sprawdź Aktualizacje",
        updatesAvailable = "Dostępne Aktualizacje", guestUser = "Gość",
        installedTitle = "Zainstalowane", nothingInstalled = "Jeszcze nic nie zainstalowano",
        nothingInstalledDesc = "Aplikacje zainstalowane przez Vyxel\nbędą tutaj",
        installedStatus = "Zainstalowane", removedStatus = "Usunięte",
        loadingApps = "Ładowanie aplikacji ze wszystkich źródeł…",
        pressBackToExit = "Naciśnij wstecz ponownie, aby wyjść",
        noApkAvailable = "Brak APK", translateTo = "Przetłumacz na",
    )

    "Swedish" -> AppStrings(
        navHome = "Hem", navSearch = "Sök", navInstalled = "Installerat",
        navProfile = "Profil", navSettings = "Inställningar",
        searchHint = "Sök på GitHub, GitLab, F-Droid…",
        trendingApps = "Populära Appar", allSources = "Alla Källor",
        searching = "Söker i alla källor…", fetchingMore = "Hämtar från fler källor…",
        noResultsFound = "Inga resultat hittades",
        tryDifferent = "Prova andra sökord eller ta bort filter",
        install = "Installera", download = "Ladda ned", downloadOnly = "Bara Ladda ned",
        uninstall = "Avinstallera", cancel = "Avbryt", save = "Spara",
        edit = "Redigera", retry = "Försök Igen", apply = "Tillämpa", refresh = "Uppdatera",
        back = "Tillbaka", skipVersion = "Hoppa över denna version",
        checkingRelease = "Kontrollerar senaste version…",
        stableRelease = "Stabil version", whatsNew = "Nyheter",
        noApkFound = "Ingen APK hittad i denna version.",
        downloading = "Laddar ned…",
        stars = "Stjärnor", forks = "Förgreningar", codingLanguage = "Språk",
        about = "Om", translate = "Översätt", compare = "Jämför",
        version = "Version", featured = "UTVALD", openInBrowser = "Öppna i Webbläsare",
        updateAvailable = "Uppdatering Tillgänglig", installedBadge = "✓  Installerat",
        screenshots = "Skärmdumpar", release = "Version",
        noDescAvailable = "Ingen beskrivning tillgänglig.",
        translatedRedo = "Översatt · Gör om",
        sectionRecommended = "⭐ Rekommenderat för Dig",
        sectionTrending = "🔥 Trending", sectionMedia = "🎬 Medier & Underhållning",
        sectionTools = "🛠 Verktyg", sectionGames = "🎮 Spel & Emulatorer",
        sectionBrowsers = "🌐 Webbläsare & Integritet",
        sectionProductivity = "📋 Produktivitet", sectionSecurity = "🔒 Säkerhet",
        sectionDevTools = "💻 Utvecklarverktyg", sectionPhotoVideo = "📸 Foto & Video",
        sectionMusic = "🎵 Musik & Ljud", sectionFinance = "💰 Ekonomi",
        sectionEducation = "📚 Utbildning", sectionFitness = "💪 Fitness & Hälsa",
        sectionArtDesign = "🎨 Konst & Design", sectionNews = "🗞 Nyheter",
        sectionSocial = "💬 Socialt", sectionCloudStorage = "☁️ Molnlagring",
        sectionCooking = "🍳 Mat & Recept",
        settingsTitle = "Inställningar", appearance = "UTSEENDE", themeColor = "TEMAFÄRG",
        fontSection = "TECKENSNITT", languageSection = "SPRÅK",
        githubSection = "GITHUB", aboutSection = "OM",
        amoledOverride = "AMOLED-override",
        amoledOverrideDesc = "Tvinga rent svart bakgrund på mörkt tema",
        materialYou = "Material You (Monet)",
        materialYouDesc = "Hämtar färger från din bakgrundsbild",
        personalAccessToken = "Personlig Åtkomsttoken",
        tokenRequired = "Krävs för GitHub-sökning",
        saveToken = "Spara Token", versionLabel = "Version",
        followSystem = "📱  Följ System",
        profileTitle = "Profil", displayName = "Visningsnamn", emailAddress = "E-postadress",
        supportFeedbackTitle = "Support & Feedback", sendFeedback = "Skicka Feedback",
        sendFeedbackDesc = "Föreslå funktioner eller rapportera fel",
        supportProject = "Stöd Projektet",
        supportProjectDesc = "Ge stjärna på GitHub eller bidra",
        shareVyxel = "Dela Vyxel", shareVyxelDesc = "Berätta för dina vänner",
        favourites = "Favoriter", recentlyViewed = "Nyligen Sett",
        installHistory = "Installationshistorik",
        installHistoryHint = "Tryck för att ominstallera en version",
        checkForUpdates = "Sök Uppdateringar",
        updatesAvailable = "Uppdateringar Tillgängliga", guestUser = "Gäst",
        installedTitle = "Installerat", nothingInstalled = "Inget installerat ännu",
        nothingInstalledDesc = "Appar du installerar via Vyxel\nvisas här",
        installedStatus = "Installerat", removedStatus = "Borttaget",
        loadingApps = "Laddar appar från alla källor…",
        pressBackToExit = "Tryck tillbaka igen för att avsluta",
        noApkAvailable = "Ingen APK Tillgänglig", translateTo = "Översätt till",
    )

    else -> AppStrings() // English default
}
